"""A single self-contained HTML page summarising the whole pipeline.

Images are embedded as base64 so the file works offline and travels as one
artefact. Built from whatever `reports/` currently holds.
"""
# ruff: noqa: E501  (HTML template lines)

from __future__ import annotations

import base64
from pathlib import Path

import pandas as pd

from ..config import Config


def _img(path: Path) -> str:
    if not path.exists():
        return f"<p class='missing'>[{path.name} not generated yet]</p>"
    b64 = base64.b64encode(path.read_bytes()).decode()
    return f"<img src='data:image/png;base64,{b64}' alt='{path.stem}'>"


def _table(path: Path, index: bool = True) -> str:
    if not path.exists():
        return f"<p class='missing'>[{path.name} not generated yet]</p>"
    df = pd.read_csv(path, index_col=0 if index else None)
    return df.to_html(border=0, classes="tbl", float_format=lambda v: f"{v:.3f}")


_CSS = """
:root { --fg:#1b1b1b; --muted:#666; --line:#e3e3e3; --accent:#1f77b4; }
* { box-sizing:border-box; }
body { font:15px/1.55 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;
       color:var(--fg); max-width:960px; margin:0 auto; padding:32px 20px; }
h1 { font-size:24px; margin:0 0 4px; }
h2 { font-size:17px; margin:34px 0 10px; border-bottom:2px solid var(--line); padding-bottom:4px; }
.sub { color:var(--muted); margin:0 0 8px; }
img { max-width:100%; height:auto; border:1px solid var(--line); border-radius:6px; }
pre { background:#f6f8fa; border:1px solid var(--line); border-radius:6px; padding:14px;
      white-space:pre-wrap; font-size:13px; }
table.tbl { border-collapse:collapse; font-size:13px; margin:6px 0; }
table.tbl td, table.tbl th { border:1px solid var(--line); padding:4px 10px; text-align:right; }
table.tbl th { background:#f6f8fa; }
table.tbl td:first-child, table.tbl th:first-child { text-align:left; }
.missing { color:#b00; font-size:13px; }
footer { color:var(--muted); font-size:12px; margin-top:40px; border-top:1px solid var(--line); padding-top:12px; }
"""


def build_dashboard(cfg: Config, *, brief: str = "", chronology: pd.DataFrame | None = None) -> Path:
    r = cfg.reports_dir
    chron_html = ""
    if chronology is not None and not chronology.empty:
        c = chronology.tail(10).copy()
        c["start"] = pd.to_datetime(c["start"]).dt.strftime("%Y-%m")
        c["end"] = pd.to_datetime(c["end"]).dt.strftime("%Y-%m")
        chron_html = c.to_html(border=0, classes="tbl", index=False)

    html = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Semiconductor Cycle Intelligence</title><style>{_CSS}</style></head><body>
<h1>Semiconductor Cycle Intelligence</h1>
<p class="sub">Latent cycle factor &rarr; billings nowcast &rarr; cost-aware equity strategy, on free public data.</p>

<h2>1 &nbsp; The cycle</h2>
<p class="sub">Dynamic factor model over WSTS regional billings, Taiwan revenue and SOX momentum; Bry&ndash;Boschan phase dating.</p>
{_img(r / "cycle_factor.png")}
{f"<h3 style='font-size:14px;margin:14px 0 4px'>recent phases</h3>{chron_html}" if chron_html else ""}

<h2>2 &nbsp; The nowcast</h2>
<p class="sub">Walk-forward, purge + embargo, 240 out-of-sample months. Skill vs an autoregressive point-in-time benchmark.</p>
{_img(r / "nowcast_oos_h3.png")}
<div style="display:flex;gap:24px;flex-wrap:wrap">
<div>{_table(r / "scoreboard_h3.csv")}</div>
</div>

<h2>3 &nbsp; The strategy</h2>
<p class="sub">Cycle-timing overlay on SOXX, 10&nbsp;bps cost. A risk overlay, not alpha.</p>
{_img(r / "strategy_dashboard.png")}
<div style="display:flex;gap:24px;flex-wrap:wrap;align-items:flex-start">
<div>{_table(r / "strategy_stats.csv")}</div>
<div>{_table(r / "strategy_robustness.csv")}</div>
</div>

<h2>4 &nbsp; Real-time checks</h2>
<p class="sub">Timing off the forward nowcast beats timing off the coincident factor; neither beats buy &amp; hold on a drawdown-light window. The pseudo-real-time and fully recursive factors agree.</p>
{_img(r / "realtime_timing_compare.png")}
{_img(r / "realtime_factor_compare.png")}

<h2>Brief</h2>
<pre>{brief.strip() or "(run scripts/05_report.py)"}</pre>

<footer>Generated by <code>scripts/07_dashboard.py</code>. Educational / research use only &mdash; not investment advice.</footer>
</body></html>"""

    out = r / "dashboard.html"
    out.write_text(html, encoding="utf-8")
    return out
